OPENQASM 3.0;
include "stdgates.inc";
bit[2] ans;
qubit[3] var;
qubit[3] conj;
qubit[1] anci;
h var[1];
h var[2];
x conj[0];
x conj[1];
x conj[2];
x var[1];
x var[2];
ccx var[1], var[2], conj[0];
x var[2];
ccx var[1], var[2], conj[1];
x var[1];
x var[2];
ccx var[1], var[2], conj[2];
x var[2];
ccx conj[0], conj[1], anci[0];
ccx conj[2], anci[0], var[0];
ccx conj[0], conj[1], anci[0];
x var[2];
ccx var[1], var[2], conj[2];
x var[1];
x var[2];
ccx var[1], var[2], conj[1];
x var[2];
ccx var[1], var[2], conj[0];
x var[1];
x var[2];
h var[1];
h var[2];
x var[0];
x var[1];
x var[2];
h var[0];
ccx var[1], var[2], var[0];
h var[0];
x var[0];
x var[1];
x var[2];
h var[0];
h var[1];
h var[2];
ans[0] = measure var[1];
ans[1] = measure var[2];
