OPENQASM 3.0;
include "stdgates.inc";
bit[4] cout;
qubit[3] addr;
qubit[8] rout;
qubit[8] ram;
qubit[1] qout;
x addr[1];
x ram[0];
x ram[2];
x ram[7];
x rout[7];
cx addr[0], rout[3];
cx rout[3], rout[7];
ccx addr[1], rout[3], rout[1];
cx rout[1], rout[3];
ccx addr[1], rout[7], rout[5];
cx rout[5], rout[7];
ccx addr[2], rout[1], rout[0];
ccx addr[2], rout[3], rout[2];
ccx addr[2], rout[5], rout[4];
ccx addr[2], rout[7], rout[6];
cx rout[0], rout[1];
cx rout[2], rout[3];
cx rout[4], rout[5];
cx rout[6], rout[7];
ccx rout[7], ram[7], qout[0];
ccx rout[6], ram[6], qout[0];
ccx rout[5], ram[5], qout[0];
ccx rout[4], ram[4], qout[0];
ccx rout[3], ram[3], qout[0];
ccx rout[2], ram[2], qout[0];
ccx rout[1], ram[1], qout[0];
ccx rout[0], ram[0], qout[0];
cx rout[6], rout[7];
cx rout[4], rout[5];
cx rout[2], rout[3];
cx rout[0], rout[1];
ccx addr[2], rout[7], rout[6];
ccx addr[2], rout[5], rout[4];
ccx addr[2], rout[3], rout[2];
ccx addr[2], rout[1], rout[0];
cx rout[5], rout[7];
ccx addr[1], rout[7], rout[5];
cx rout[1], rout[3];
ccx addr[1], rout[3], rout[1];
cx rout[3], rout[7];
cx addr[0], rout[3];
cout[0] = measure addr[0];
cout[1] = measure addr[1];
cout[2] = measure addr[2];
cout[3] = measure qout[0];
